/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.AuthController;
import Controllers.PenjualanController;
import Controllers.PelangganController;
import Controllers.DashboardController;
import Controllers.HelpController;
import Controllers.PembelianController;
import Controllers.KategoriProdukController;
import Controllers.ReportController;
import Controllers.Controller;
import Controllers.SupplierController;
import Controllers.ProdukController;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Jessica
 */
public class MainForm extends javax.swing.JFrame {
    JPopupMenu popupMenuMaster, popupMenuTransaksi, popupMenuLaporan, popupMenuUser;
    ArrayList<JMenuItem> LMI = new ArrayList<>();
    Controller tmp;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        Setup();
        RefineryUtilities.centerFrameOnScreen(this);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LDashboard = new javax.swing.JLabel();
        LMaster = new javax.swing.JLabel();
        LTransaksi = new javax.swing.JLabel();
        LLaporan = new javax.swing.JLabel();
        LHelp = new javax.swing.JLabel();
        LUser = new javax.swing.JLabel();
        PUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(456, 400));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        LDashboard.setForeground(new java.awt.Color(204, 204, 204));
        LDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LDashboard.setText("  Dashboard");
        LDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LDashboardMouseClicked(evt);
            }
        });
        jPanel1.add(LDashboard);

        LMaster.setForeground(new java.awt.Color(204, 204, 204));
        LMaster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LMaster.setText("  Master");
        LMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMasterMouseClicked(evt);
            }
        });
        jPanel1.add(LMaster);

        LTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        LTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTransaksi.setText("  Transaksi");
        LTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LTransaksiMouseClicked(evt);
            }
        });
        jPanel1.add(LTransaksi);

        LLaporan.setForeground(new java.awt.Color(204, 204, 204));
        LLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LLaporan.setText("  Laporan");
        LLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LLaporanMouseClicked(evt);
            }
        });
        jPanel1.add(LLaporan);

        LHelp.setForeground(new java.awt.Color(204, 204, 204));
        LHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LHelp.setText("  Help");
        LHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LHelpMouseClicked(evt);
            }
        });
        jPanel1.add(LHelp);

        LUser.setForeground(new java.awt.Color(204, 204, 204));
        LUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LUser.setText("User");
        LUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LUserMouseClicked(evt);
            }
        });
        jPanel1.add(LUser);

        javax.swing.GroupLayout PUtamaLayout = new javax.swing.GroupLayout(PUtama);
        PUtama.setLayout(PUtamaLayout);
        PUtamaLayout.setHorizontalGroup(
            PUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PUtamaLayout.setVerticalGroup(
            PUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Setup(){
        
        LDashboard.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/home.png")).getImage().getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
        LMaster.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/db.png")).getImage().getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
        LTransaksi.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/trans.png")).getImage().getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
        LLaporan.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/chart.png")).getImage().getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
        LHelp.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/help.png")).getImage().getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
        LUser.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/user.png")).getImage().getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
        
        DashboardController d = new DashboardController();
        changeJIF(d);
        resetColorTab();
        LDashboard.setForeground(new Color(102,102,102));
        
        popupMenuMaster = new JPopupMenu();
        popupMenuMaster.setBackground(new Color(0,51,51));
        popupMenuMaster.setForeground(new Color(204,204,204));
        
        makeMenuItems(popupMenuMaster,"Produk","/Assets/icon/produk.png", new ProdukController(), LMaster);
        popupMenuMaster.addSeparator(); 
        makeMenuItems(popupMenuMaster,"Kategori Produk","/Assets/icon/kategori.png", new KategoriProdukController(), LMaster);
        popupMenuMaster.addSeparator(); 
        makeMenuItems(popupMenuMaster,"Pelanggan","/Assets/icon/pelanggan.png", new PelangganController(), LMaster);
        popupMenuMaster.addSeparator(); 
        makeMenuItems(popupMenuMaster,"Supplier","/Assets/icon/supplier.png", new SupplierController(), LMaster);
        
        
        popupMenuTransaksi = new JPopupMenu();
        popupMenuTransaksi.setBackground(new Color(0,51,51));
        popupMenuTransaksi.setForeground(new Color(204,204,204));
        
        makeMenuItems(popupMenuTransaksi,"Pembelian","/Assets/icon/transaksi.png", new PembelianController(), LTransaksi);
        popupMenuTransaksi.addSeparator(); 
        makeMenuItems(popupMenuTransaksi,"Penjualan","/Assets/icon/transaksi.png", new PenjualanController(), LTransaksi);
        
        popupMenuLaporan = new JPopupMenu();
        popupMenuLaporan.setBackground(new Color(0,51,51));
        popupMenuLaporan.setForeground(new Color(204,204,204));
        
        makeMenuItems(popupMenuLaporan,"Penjualan","/Assets/icon/transaksi.png", new ReportController("penjualan"), LLaporan);
        popupMenuLaporan.addSeparator(); 
        makeMenuItems(popupMenuLaporan,"Pelanggan","/Assets/icon/pelanggan.png", new ReportController("pelanggan"), LLaporan);
        
        popupMenuUser = new JPopupMenu();
        popupMenuUser.setBackground(new Color(0,51,51));
        popupMenuUser.setForeground(new Color(204,204,204));
        
        makeMenuItems(popupMenuUser,"Logout        ","/Assets/icon/logout.png");
    }
    private void LDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDashboardMouseClicked
        DashboardController d = new DashboardController();
        changeJIF(d);
        resetColorTab();
        LDashboard.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_LDashboardMouseClicked

    private void LMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMasterMouseClicked
        popupMenuMaster.show(LMaster, 0, jPanel1.getHeight());
    }//GEN-LAST:event_LMasterMouseClicked

    private void LTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LTransaksiMouseClicked
        popupMenuTransaksi.show(LTransaksi, 0, jPanel1.getHeight());
    }//GEN-LAST:event_LTransaksiMouseClicked

    private void LLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LLaporanMouseClicked
        popupMenuLaporan.show(LLaporan, 0, jPanel1.getHeight());
    }//GEN-LAST:event_LLaporanMouseClicked

    private void LHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LHelpMouseClicked
        HelpController d = new HelpController();
        changeJIF(d);
        resetColorTab();
        LHelp.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_LHelpMouseClicked

    private void LUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LUserMouseClicked
        popupMenuUser.show(LUser, 0, jPanel1.getHeight());
    }//GEN-LAST:event_LUserMouseClicked


    
    void changeJIF(Controller d){
        if(tmp != null){
            tmp.getView().dispose();
        }
        PUtama.removeAll();
        try {
            PUtama.add(d.getView());
            d.getView().setMaximum(true);
            d.getView().setFocusable(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        d.showView();
        tmp = d;
    }
    
    void resetColorTab(){
        LDashboard.setForeground(new Color(204, 204, 204));
        LMaster.setForeground(new Color(204, 204, 204));
        LTransaksi.setForeground(new Color(204, 204, 204));
        LLaporan.setForeground(new Color(204, 204, 204));
        LHelp.setForeground(new Color(204, 204, 204));
        LUser.setForeground(new Color(204, 204, 204));
        
        for (int i = 0; i < LMI.size()-1; i++) {
            LMI.get(i).setForeground(new Color(204, 204, 204));
        }
    }
    
    void makeMenuItems(JPopupMenu jpm,String text, String loc, Controller jif, JLabel jb){
        ImageIcon imageIcon= new ImageIcon(new javax.swing.ImageIcon(getClass().getResource(loc)).getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH));
        
        JMenuItem jm = new JMenuItem(text);
        jm.setBackground(new Color(0, 51, 51));
        jm.setForeground(new Color(204, 204, 204));
        jm.setIcon(imageIcon);
        jm.setSize(jb.getPreferredSize().width, 32);
        jm.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jpm.add(jm);
        
        jm.addActionListener((ActionEvent e) -> {
            changeJIF(jif);
            resetColorTab();
            jb.setForeground(new Color(102,102,102));
            jm.setForeground(new Color(102,102,102));
        });
        LMI.add(jm);
    }
    
    void makeMenuItems(JPopupMenu jpm,String text, String loc){
        ImageIcon imageIcon= new ImageIcon(new javax.swing.ImageIcon(getClass().getResource(loc)).getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH));
        
        JMenuItem jm = new JMenuItem(text);
        jm.setBackground(new Color(0, 51, 51));
        jm.setForeground(new Color(204, 204, 204));
        jm.setIcon(imageIcon);
        jm.setSize(jpm.getPreferredSize().width, 32);
        jm.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jpm.add(jm);
        
        jm.addActionListener((ActionEvent e) -> {
            MainForm.this.setVisible(false);
            (new AuthController()).show();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LDashboard;
    private javax.swing.JLabel LHelp;
    private javax.swing.JLabel LLaporan;
    private javax.swing.JLabel LMaster;
    private javax.swing.JLabel LTransaksi;
    private javax.swing.JLabel LUser;
    private javax.swing.JPanel PUtama;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
